version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts
    user: root
    ports:
      - "8090:8080"
      - "50000:50000"
    container_name: jenkins
    volumes:
      - jenkins:/var/jenkins_home
      - /opt/jdk-17.0.8+7:/opt/jdk-17.0.8+7
volumes:
  jenkins:
